// Tax Collection/tax-calculation/src/TaxCalculationForm.jsx
import React, { useState } from 'react';

const TaxCalculationForm = () => {
    const [income, setIncome] = useState('');
    const [taxRate, setTaxRate] = useState('');
    const [tax, setTax] = useState(null);

    const calculateTax = (e) => {
        e.preventDefault();
        const incomeNum = parseFloat(income);
        const taxRateNum = parseFloat(taxRate);

        if (!isNaN(incomeNum) && !isNaN(taxRateNum)) {
            const calculatedTax = incomeNum * (taxRateNum / 100);
            setTax(calculatedTax);
        }
    };

    return (
        <div>
            <h2>Tax Calculation Form</h2>
            <form onSubmit={calculateTax}>
                <div>
                    <label>Income:</label>
                    <input
                        type="number"
                        value={income}
                        onChange={(e) => setIncome(e.target.value)}
                        placeholder="Enter your income"
                    />
                </div>
                <div>
                    <label>Tax Rate (%):</label>
                    <input
                        type="number"
                        value={taxRate}
                        onChange={(e) => setTaxRate(e.target.value)}
                        placeholder="Enter tax rate"
                    />
                </div>
                <button type="submit">Calculate Tax</button>
            </form>
            {tax !== null && (
                <div>
                    <h3>Calculated Tax: INR{tax.toFixed(2)}</h3>
                </div>
            )}
        </div>
    );
};

export default TaxCalculationForm;

// Tax Collection/tax-calculation1/src/app/tax-calculation-form/tax-calculation-form.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-tax-calculation-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './tax-calculation-form.component.html',
  styleUrls: ['./tax-calculation-form.component.css']
})
export class TaxCalculationFormComponent {
  income: number | null = null;
  taxRate: number | null = null;
  tax: number | null = null;

  calculateTax(): void {
    if (this.income !== null && this.taxRate !== null) {
      this.tax = this.income * (this.taxRate / 100);
    }
  }
}

<div>
  <h2>Tax Calculation Form</h2>
  <form (ngSubmit)="calculateTax()">
    <div>
      <label for="income">Income:</label>
      <input
        type="number"
        id="income"
        [(ngModel)]="income"
        name="income"
        placeholder="Enter your income"
        required
      />
    </div>
    <div>
      <label for="taxRate">Tax Rate (%):</label>
      <input
        type="number"
        id="taxRate"
        [(ngModel)]="taxRate"
        name="taxRate"
        placeholder="Enter tax rate"
        required
      />
    </div>
    <button type="submit">Calculate Tax</button>
  </form>
  <div *ngIf="tax !== null">
    <h3>Calculated Tax: INR{{ tax.toFixed(2) }}</h3>
  </div>
</div>
